export const core = [
  {
    avatar: './Three/facebook.png',
    name: 'BTC',
    title: 'CA:ArXETDYEcKmPWTN7CbLtAtw3bruJbrtwb3FD1RnvXFuf',
    org: 'BTC',
    orgLink: 'https://btc.543x.com/',
    desc: 'Bitcoin: A Peer-to-Peer Electronic Cash System',
    links: [
      { icon: 'github', link: 'https://btc.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/83XaC2jg2FqHMVjcUnHZmcgRL5MvgD45B9FxbK8evosk' },
    ],
    sponsor: 'https://btc.543x.com/',
  },
  {
    avatar: './Three/adsmanager.png',
    name: 'solana',
    title: 'CA:ATvWFEriuCm5ES26sXncc8tYBiDnjGbahzG6fp3uYQBk',
    org: 'solana',
    orgLink: 'https://accounts.binance.com/en/register?ref=11131007',
    desc: 'Native cryptocurrency of the Solana blockchain.',
    links: [
      { icon: 'github', link: 'http://sol.543x.com/' },
      { icon: 'twitter', link: 'https://accounts.binance.com/en/register?ref=11131007' },
      { icon: 'mastodon', link: 'http://sol.543x.com/' },
    ],
    sponsor: 'https://accounts.binance.com/en/register?ref=11131007',
  },
  {
    avatar: './Three/metaquest.png',
    name: 'USDC',
    title: 'CA:3zwVdm5GkUFfJDMJSaMGjQtaMA7sqVWpCynoXcJ6kaX7',
    org: 'USDC',
    orgLink: 'http://usdc.543x.com/',
    desc: 'USD-pegged stablecoin for digital transactions.',
    links: [
      { icon: 'github', link: 'http://usdc.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y' },
      { icon: 'mastodon', link: 'http://usdc.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y',
  },
  {
    avatar: './Three/messengerdesktop.png',
    name: 'BUSD',
    title: 'CA:J8ctjxNqi8vsKS5awupxoe3oK2qzcD3haJdrU8NnwP3x',
    org: 'BUSD',
    orgLink: 'http://busd.543x.com',
    desc: 'Rare digital collectibles on the blockchain.',
    links: [
      { icon: 'github', link: 'http://busd.543x.com' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/2EzPinaN1FcDu7jB5YxFYERbhxMYiT3bYNiP3sL5jfdB' },
      { icon: 'mastodon', link: 'http://busd.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/2EzPinaN1FcDu7jB5YxFYERbhxMYiT3bYNiP3sL5jfdB',
  },
  {
    avatar: './Three/eth.png',
    name: 'Eth',
    title: 'CA:EBBHUma1N1pAZBFjSHEqRRaZ6zGYjWsbiQDrkftFSQuh',
    org: 'Eth',
    orgLink: 'https://eth.543x.com',
    desc: 'decentralized platform for smart contracts DApps.',
    links: [
      { icon: 'github', link: 'https://eth.543x.com' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/2EzPinaN1FcDu7jB5YxFYERbhxMYiT3bYNiP3sL5jfdB' },
      { icon: 'mastodon', link: 'https://eth.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/2EzPinaN1FcDu7jB5YxFYERbhxMYiT3bYNiP3sL5jfdB',
  },
  {
    avatar: './Three/officemobile.png',
    name: 'FDUSD',
    title: 'CA:6fyVxagdYGtYv1u117cctvrYGJQwEYmg8LivELTT5yZL',
    org: 'FDUSD',
    orgLink: 'https://fdusd.543x.com/',
    desc: 'Girlfriend\'s worth, usually used humorously',
    links: [
      { icon: 'github', link: 'https://fdusd.543x.com//' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/JBdMRhuxAtMW754NceSMFPLnpPc2XAwgYZwXNUawSah5' },
      { icon: 'mastodon', link: 'https://fdusd.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/JBdMRhuxAtMW754NceSMFPLnpPc2XAwgYZwXNUawSah5',
  },
  {
    avatar: './Three/outlookmobile.png',
    name: 'PANDA',
    title: 'CA:FvWxbAxMTrYVNVrvUusjNNSLFd55CwATZ2dYnUWy4XYU',
    org: 'PANDA',
    orgLink: 'http://panda.543x.com/',
    desc: 'Chinese gold coins with varying panda designs.',
    links: [
      { icon: 'github', link: 'http://panda.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/6xvVWCy9KtkA7DnVtVUJqmMorrYxUS3VUcUYAzM59gXe' },
      { icon: 'mastodon', link: 'http://panda.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/6xvVWCy9KtkA7DnVtVUJqmMorrYxUS3VUcUYAzM59gXe',
  },
  {
    avatar: './Three/teamsmobile.png',
    name: 'SATOSHI',
    title: 'CA:F37bUysKLHJBvFNCxAfGhDMArbZdk7LY1xAEc2MaqZja',
    org: 'SATOSHI',
    orgLink: 'http://satoshi.543x.com/',
    desc: '1 Bitcoin is equivalent to 100 million Satoshi.',
    links: [
      { icon: 'github', link: 'http://satoshi.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/5TMTjmESoG6Hqbwrv9AeweoFyCet8Min2G48oQbhbTp6' },
      { icon: 'mastodon', link: 'http://satoshi.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/5TMTjmESoG6Hqbwrv9AeweoFyCet8Min2G48oQbhbTp6',
  },
  {
    avatar: './Three/xboxgamepass.png',
    name: 'TON',
    title: 'CA:F37bUysKLHJBvFNCxAfGhDMArbZdk7LY1xAEc2MaqZja',
    org: 'TON',
    orgLink: 'http://ton.543x.com/',
    desc: 'Efficient, low-cost, decentralized blockchain platform',
    links: [
      { icon: 'github', link: 'http://ton.543x.com/' },
      { icon: 'twitter', link: 'https://accounts.binance.com/en/register?ref=11131007' },
      { icon: 'mastodon', link: 'http://ton.543x.com/' },
    ],
    sponsor: 'https://accounts.binance.com/en/register?ref=11131007',
  },
  {
    avatar: './Three/skype.png',
    name: 'USDT',
    title: 'CA:45t4Cpoj5uZFmurz2bD1pEmXD4x1WaD3kSnetpHx9ZNi',
    org: 'USDT',
    orgLink: 'https://usdt.543x.com/',
    desc: 'USD-pegged stablecoin for blockchain transactions.',
    links: [
      { icon: 'github', link: 'https://usdt.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/BSo8Z58sYiAnmTkEX5XFQLPxGERD3pgDKdVQtHneSbkJ' },
      { icon: 'mastodon', link: 'https://usdt.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/BSo8Z58sYiAnmTkEX5XFQLPxGERD3pgDKdVQtHneSbkJ',
  },
  {
    avatar: './Three/amazon-shopping.png',
    name: 'SHIB',
    title: 'CA:45t4Cpoj5uZFmurz2bD1pEmXD4x1WaD3kSnetpHx9ZNi',
    org: 'SHIB',
    orgLink: 'http://shib.543x.com/',
    desc: 'It works right now, there is no need for a sidechain.',
    links: [
      { icon: 'github', link: 'http://shib.543x.com/' },
      { icon: 'twitter', link: 'https://accounts.binance.com/en/register?ref=11131007' },
      { icon: 'mastodon', link: 'http://shib.543x.com/' },
    ],
    sponsor: 'https://accounts.binance.com/en/register?ref=11131007',
  },
  {
    avatar: './Three/jon-bloomer.png',
    name: 'NO',
    title: 'CA:8FSGagHqgjWDb3FKz8DrXuPjf5U4eX26YTmpTpk1iYsG',
    org: 'NO',
    orgLink: 'http://no.543x.com/',
    desc: 'An internet meme used to express emotion and create humor',
    links: [
      { icon: 'github', link: 'http://no.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/Bz1kKXV74cznsVJSu4cPcdrD2ZbCv6raez9Bq5Edmtgw' },
      { icon: 'mastodon', link: 'http://no.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/Bz1kKXV74cznsVJSu4cPcdrD2ZbCv6raez9Bq5Edmtgw',
  },
  {
    avatar: './Three/amazon-photos.png',
    name: 'CLOWN',
    title: 'CA:Hv4D1ohDS6xTiBfHU4gXxCLUM5ekFAb74s9J3H5TzdBx',
    org: 'CLOWN',
    orgLink: 'http://clown.543x.com',
    desc: 'A currency that delivers positivity, optimism, friendship and fun.',
    links: [
      { icon: 'github', link: 'http://clown.543x.com' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/5m7P7Ye2wHatH6TmFbzyNoaYvdPcnDTfzuZZPU9drbxW' },
      { icon: 'mastodon', link: 'http://clown.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/5m7P7Ye2wHatH6TmFbzyNoaYvdPcnDTfzuZZPU9drbxW',
  },
  {
    avatar: './Three/amazon-kindle.png',
    name: 'BNB',
    title: 'CA:124XZFhE8ABFYSuDZkxbkKTKjqrB7CpHCspCPsQJPQvL',
    org: 'BNB',
    orgLink: 'https://bnb.543x.com/',
    desc: 'Native cryptocurrency of the Binance platform.',
    links: [
      { icon: 'github', link: 'https://bnb.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/7CdHDxxdEFEM8MEHaEPNfzL18D8w35AkArWrd9SH7bC2' },
      { icon: 'mastodon', link: 'https://bnb.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/7CdHDxxdEFEM8MEHaEPNfzL18D8w35AkArWrd9SH7bC2',
  },
  {
    avatar: './Three/amazon-appstore.png',
    name: 'SATS',
    title: 'CA:124XZFhE8ABFYSuDZkxbkKTKjqrB7CpHCspCPsQJPQvL',
    org: 'SATS',
    orgLink: 'http://sats.543x.com/',
    desc: 'The most memeable memecoin on the Bitcoin Chain known .',
    links: [
      { icon: 'github', link: 'http://sats.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/83XaC2jg2FqHMVjcUnHZmcgRL5MvgD45B9FxbK8evosk' },
      { icon: 'mastodon', link: 'http://sats.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/83XaC2jg2FqHMVjcUnHZmcgRL5MvgD45B9FxbK8evosk',
  },
]

export const emeriti = [
  {
    avatar: './Three/pos.png',
    name: 'MIQI',
    title: 'CA:42RrRKsSPbYYcfBzBgVFHg6txmgTdiqoLttCjPJoeJWW',
    org: 'MIQI',
    orgLink: 'https://miqi.543x.com',
    desc: 'Fast, agile, strong network, strong adaptability and cute affinity.',
    links: [
      { icon: 'github', link: 'https://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/7gZYm4VQd4hTNgA9Eapdq37XLcuGjHYAq6CQ6NM2SXUu' },
      { icon: 'mastodon', link: 'https://miqi.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/7gZYm4VQd4hTNgA9Eapdq37XLcuGjHYAq6CQ6NM2SXUu',
  },
  {
    avatar: './Three/x.png',
    name: 'X',
    title: 'CA:5Pg797Jd9CFCi8MUUoh7N7g6iWsboHC2SeWs7rRyxVwe',
    org: 'X',
    orgLink: 'https://x.543x.com',
    desc: 'Features such as innovation, diversification, global exchange network, community-driven.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb' },
      { icon: 'mastodon', link: 'https://x.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb',
  },
  {
    avatar: './Three/spaces.png',
    name: 'SHEEP',
    title: 'CA:5BLtJtMYYw3QxWcXGr9fTPHAVFe766to1WRYLQYJBJrn',
    org: 'SHEEP',
    orgLink: 'https://sheep.543x.com',
    desc: 'Inspired by the snake flexibility, stealth, alertness, metamorphosis.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/GYJkxTb1WLQELBFCXgLxPACuKA1Abd3bJFPKrEPsG5m9' },
      { icon: 'mastodon', link: 'https://sheep.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/GYJkxTb1WLQELBFCXgLxPACuKA1Abd3bJFPKrEPsG5m9',
  },
  {
    avatar: './Three/dine.png',
    name: 'PEACE',
    title: 'CA:2qkVV1aJSq29RCufbc7yCcGsS7k97ZkQaZzUb9pM1Nnh',
    org: 'PEACE',
    orgLink: 'https://peace.543x.com/',
    desc: 'It has the characteristics of agile adaptation, community power.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/6YwbhVxL5DBArRaC2rSsS738wjdzTzEzPSZDwRnRSnHX' },
      { icon: 'mastodon', link: 'https://peace.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/6YwbhVxL5DBArRaC2rSsS738wjdzTzEzPSZDwRnRSnHX',
  },
  {
    avatar: './Three/fit.png',
    name: 'XRP',
    title: 'CA:2qkVV1aJSq29RCufbc7yCcGsS7k97ZkQaZzUb9pM1Nnh',
    org: 'XRP',
    orgLink: 'https://xrp.543x.com',
    desc: 'Native cryptocurrency of the Ripple network.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y' },
      { icon: 'mastodon', link: 'https://xrp.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y',
  },
  {
    avatar: './Three/owner.png',
    name: 'RATS',
    title: 'CA:2qkVV1aJSq29RCufbc7yCcGsS7k97ZkQaZzUb9pM1Nnh',
    org: 'RATS',
    orgLink: 'http://rats.543x.com',
    desc: 'The most memeable memecoin on the Bitcoin Chain  known for its significant.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y' },
      { icon: 'mastodon', link: 'http://rats.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y',
  },
  {
    avatar: './Three/cow.png',
    name: 'cow',
    title: 'CA:EMQvrURJHps2qZYb4mRb8pNRDmWjzBt57krsoc4B8cHc',
    org: 'cow',
    orgLink: 'https://cow.543x.com/',
    desc: 'It combines the characteristics of robustness, durability.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/GHNBzjJe12m37Jj9JV4Jz6cunA34oCbXcgudCocPMJ4H' },
      { icon: 'mastodon', link: 'https://cow.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/GHNBzjJe12m37Jj9JV4Jz6cunA34oCbXcgudCocPMJ4H',
  },
  {
    avatar: './Three/puma.png',
    name: 'DOGE',
    title: 'CA:AncaR5NrA9ZbDY8tWntGyb5CZAK8QhDLfGhJBG3NWwrR',
    org: 'DOGE',
    orgLink: 'http://doge.543x.com',
    desc: 'Meme based cryptocurrency known as dogecoin.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/vVTYpKUvcZHr5EJJKRefamq7u8W8eDjz7gqERAvga3R' },
      { icon: 'mastodon', link: 'http://doge.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/vVTYpKUvcZHr5EJJKRefamq7u8W8eDjz7gqERAvga3R',
  },
  {
    avatar: './Three/dave.png',
    name: 'AVAX',
    title: 'CA:3zwVdm5GkUFfJDMJSaMGjQtaMA7sqVWpCynoXcJ6kaX7',
    org: 'AVAX',
    orgLink: 'http://www.543x.com/',
    desc: 'Avalanche native token used to validate the network, vote and pay transaction fees.',
    links: [
      { icon: 'github', link: 'http://www.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y' },
      { icon: 'mastodon', link: 'http://usdc.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/AizCbr94n73ykw7iefDbXc61AjQiQEULnTJs6m5Hdc6y',
  },
  {
    avatar: './Three/discord.png',
    name: 'DONALD',
    title: 'CA:AkfGJmaS6DznynN8xA9FhbdbGGYhXSwJv5ZdC6P5TRB4',
    org: 'DONALD',
    orgLink: 'https://donald.543x.com/',
    desc: 'Inspired by Disney Donald Duck, with its unique naming and branding.',
    links: [
      { icon: 'github', link: 'https://donald.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/6Ed7Gy1aKNrvSr7srCJWowaLSEjCySmeRWK2iacEPCmw' },
      { icon: 'mastodon', link: 'https://donald.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/6Ed7Gy1aKNrvSr7srCJWowaLSEjCySmeRWK2iacEPCmw',
  },
  {
    avatar: './Three/tesla.png',
    name: 'SNAKE',
    title: 'CA:2qkVV1aJSq29RCufbc7yCcGsS7k97ZkQaZzUb9pM1Nnh',
    org: 'SNAKE',
    orgLink: 'https://snake.543x.com',
    desc: 'Inspired by the snake flexibility, stealth, alertness, metamorphosis.',
    links: [
      { icon: 'github', link: 'https://snake.543x.com' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/6YwbhVxL5DBArRaC2rSsS738wjdzTzEzPSZDwRnRSnHX' },
      { icon: 'mastodon', link: 'https://snake.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/6YwbhVxL5DBArRaC2rSsS738wjdzTzEzPSZDwRnRSnHX',
  },
  {
    avatar: './Three/pinterest.png',
    name: 'RABBIT',
    title: 'CA:ECGz3d727sk2iECrQxTkTLgSDKeiheTcPkoBZn9UWc4n',
    org: 'RABBIT',
    orgLink: 'https://rabbit.543x.com',
    desc: 'Fast, agile, strong network, strong adaptability and cute affinity.',
    links: [
      { icon: 'github', link: 'https://rabbit.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/FbrPuX8tinmx2yxwxmYGZfZQbkS8FL9gG1dzQiWMamER' },
      { icon: 'mastodon', link: 'https://rabbit.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/FbrPuX8tinmx2yxwxmYGZfZQbkS8FL9gG1dzQiWMamER',
  },
  {
    avatar: './Three/mercari.png',
    name: 'YY',
    title: 'CA:7pajZABTSzNciQaXBBeKn93DxjCZmU8fur8X3VpNG6eo',
    org: 'YY',
    orgLink: 'http://yy.543x.com',
    desc: 'A currency that delivers positivity, optimism, friendship and fun.',
    links: [
      { icon: 'github', link: 'http://yy.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/HGxSXTJhw1vGYhhCjjqSdBbwmG4cgFpJwjXK578Qz3Ms' },
      { icon: 'mastodon', link: 'http://yy.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/HGxSXTJhw1vGYhhCjjqSdBbwmG4cgFpJwjXK578Qz3Ms',
  },
  {
    avatar: './Three/playstation.png',
    name: 'GF',
    title: 'CA:4RtELABCLKgbptLRLGitdzcLrFnkhpgA57xj53QgoTTA',
    org: 'GF',
    orgLink: 'http://gf.543x.com',
    desc: 'Girlfriend worth, usually used humorously.',
    links: [
      { icon: 'github', link: 'http://gf.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/5zz1MnzBxhozPoGDGysdu4CeeMEVeJ1cay8gpgw6Motb' },
      { icon: 'mastodon', link: 'http://gf.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/5zz1MnzBxhozPoGDGysdu4CeeMEVeJ1cay8gpgw6Motb',
  },
  {
    avatar: './Three/openvpn.png',
    name: 'YAYA',
    title: 'CA:GFXzsU8XJCCLRqr7PWcK1gihEi88LVHE49HjkvcMjkiT',
    org: 'YAYA',
    orgLink: 'https://yaya.543x.com',
    desc: 'A cultural symbolic currency full of fun, love of life and friendship.',
    links: [
      { icon: 'github', link: 'https://yaya.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/Di9aeHFYeczWysnQsbNpxFgqTzJYyU9pKCovSdrhFXHQ' },
      { icon: 'mastodon', link: 'https://www.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/Di9aeHFYeczWysnQsbNpxFgqTzJYyU9pKCovSdrhFXHQ',
  },
  {
    avatar: './Three/pinterest.png',
    name: 'ORD',
    title: 'CA:B96wBokgFf5KsuPra3dSnd3nPeiY3fAD48bAshMALQ44',
    org: 'ORD',
    orgLink: 'http://ord.543x.com',
    desc: 'It works right now, there is no need for a sidechain, the only token needed is bitcoin itself.',
    links: [
      { icon: 'github', link: 'http://ord.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/6u1nMUVkTVmSvvdjvVTJUPKP7ZoFLrbah3YtFnTa9YoA' },
      { icon: 'mastodon', link: 'https://www.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/6u1nMUVkTVmSvvdjvVTJUPKP7ZoFLrbah3YtFnTa9YoA',
  },
  {
    avatar: './Three/wordpress.png',
    name: 'CAT',
    title: 'CA:nVS6UVNVL2zQsorZpqmsrR527eqGacMAHtSV7tHKci7',
    org: 'CAT',
    orgLink: 'http://cat.543x.com',
    desc: 'An elegant and unique cat-themed platform for trading cat supplies.',
    links: [
      { icon: 'github', link: 'https://www.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/9oRdiNMEPegLEmczr55zhTygRymQn44D7Ry5Cduj4VXv' },
      { icon: 'mastodon', link: 'http://cat.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/9oRdiNMEPegLEmczr55zhTygRymQn44D7Ry5Cduj4VXv',
  },
  {
    avatar: './Three/flipkart.png',
    name: 'QQ',
    title: 'CA:6nr68C4TW9ZTXddKp3QHHcbaQyRMiPPeqqkUcf2wjU2d',
    org: 'QQ',
    orgLink: 'http://qq.543x.com/',
    desc: 'An internet meme used to express emotion and create humor.',
    links: [
      { icon: 'github', link: 'http://qq.543x.com/'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/83fGy9Fgm83CA44DU8NmhLfF2Bjq8v6dqsLcQN6NRDwm' },
      { icon: 'mastodon', link: 'http://qq.543x.com/'},
    ],
    sponsor: 'https://app.meteora.ag/pools/83fGy9Fgm83CA44DU8NmhLfF2Bjq8v6dqsLcQN6NRDwm',
  },
  {
    avatar: './Three/bloomberg.png',
    name: 'MIMI',
    title: 'CA:A8sv51gvHR5a9wynBAf88SmJS7YZ5NpurPTSpeK52kLk',
    org: 'MIMI',
    orgLink: 'https://mimi.543x.com',
    desc: 'Sweet and cute, fashionable and changeable, stable and reliable, by integrating these qualities.',
    links: [
      { icon: 'github', link: 'https://www.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/6Ed7Gy1aKNrvSr7srCJWowaLSEjCySmeRWK2iacEPCmw' },
      { icon: 'mastodon', link: 'https://mimi.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/6Ed7Gy1aKNrvSr7srCJWowaLSEjCySmeRWK2iacEPCmw',
  },
  {
    avatar: './Three/walmart.png',
    name: 'RAT',
    title: 'CA:DaZacZ6z8jAMgwBsMsGfFjuUeVpnoTxTLMkweSXgUyap',
    org: 'RAT',
    orgLink: 'https://rat.543x.com',
    desc: 'It has the characteristics of agile adaptation, community power, hidden security.',
    links: [
      { icon: 'github', link: 'https://rat.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/AEgbTbDjXX6PYgQ6DdxCmF185hSwECueVyyFg2HsXNdo' },
      { icon: 'mastodon', link: 'https://rat.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/AEgbTbDjXX6PYgQ6DdxCmF185hSwECueVyyFg2HsXNdo',
  },
  {
    avatar: './Three/baidu.png',
    name: 'monkey',
    title: 'CA:FvWxbAxMTrYVNVrvUusjNNSLFd55CwATZ2dYnUWy4XYU',
    org: 'monkey',
    orgLink: 'https://monkey.543x.com',
    desc: 'It combines lively wit, community mutual assistance, adventure exploration, fun entertainment .',
    links: [
      { icon: 'github', link: 'https://monkey.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/6JZ53cKczUmwAqz8F59TZ7ur84AjAgLFWqWNauhsdhFY' },
      { icon: 'mastodon', link: 'https://monkey.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/6JZ53cKczUmwAqz8F59TZ7ur84AjAgLFWqWNauhsdhFY',
  },
  {
    avatar: './Three/callofduty_companion.png',
    name: 'SEAL',
    title: 'CA:CzA7tZRbUBtfzJRUDRBf7V1YQFJJ2pLhajUVjKBm8Ahu',
    org: 'SEAL',
    orgLink: 'https://seal.543x.com',
    desc: 'Inspired by the Navy SEALs, it emphasizes high security, covert transactions and global adaptability.',
    links: [
      { icon: 'github', link: 'https://seal.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/GbCVRoqC57eKEdgWo3oBkgtX64Ru7d7Evow5oxNKDWdW' },
      { icon: 'mastodon', link: 'https://www.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/GbCVRoqC57eKEdgWo3oBkgtX64Ru7d7Evow5oxNKDWdW',
  },
  {
    avatar: './Three/Chicken.png',
    name: 'Chicken',
    title: 'CA:ECGz3d727sk2iECrQxTkTLgSDKeiheTcPkoBZn9UWc4n',
    org: 'Chicken',
    orgLink: 'https://rabbit.543x.com',
    desc: 'Fast, agile, strong network, strong adaptability and cute affinity.',
    links: [
      { icon: 'github', link: 'https://rabbit.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/FbrPuX8tinmx2yxwxmYGZfZQbkS8FL9gG1dzQiWMamER' },
      { icon: 'mastodon', link: 'https://rabbit.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/FbrPuX8tinmx2yxwxmYGZfZQbkS8FL9gG1dzQiWMamER',
  },
  {
    avatar: './Three/words2.png',
    name: 'dragon',
    title: 'CA:5Pg797Jd9CFCi8MUUoh7N7g6iWsboHC2SeWs7rRyxVwe',
    org: 'dragon',
    orgLink: 'https://dragon.543x.com',
    desc: 'Mysterious, unique, possessing inner strength, exploring the unknown.',
    links: [
      { icon: 'github', link: 'https://dragon.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb' },
      { icon: 'mastodon', link: 'https://dragon.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb',
  },
  {
    avatar: './Three/lendmn.png',
    name: 'OTTER',
    title: 'CA:7BkF2u2nUe3MrTUXY2sYdyuCQHrDBtrRzHqARrRWSg7g',
    org: 'OTTER',
    orgLink: 'https://otter.543x.com',
    desc: 'With characteristics such as agile adaptability, community cooperation.',
    links: [
      { icon: 'github', link: 'https://otter.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/9XeEoYSMyG5tWpNKMBKivsbbjfjrPj2rFBQUEut3vDVu' },
      { icon: 'mastodon', link: 'https://otter.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/9XeEoYSMyG5tWpNKMBKivsbbjfjrPj2rFBQUEut3vDVu',
  },
  {
    avatar: './Three/words2.png',
    name: 'pepe',
    title: 'CA:53riQbBXCEFcuxZKBv98QRZhgPgkwpwpRwvGtWqUBd1u',
    org: 'pepe',
    orgLink: 'https://pepe.543x.com',
    desc: 'Rare digital collectibles on the blockchain.',
    links: [
      { icon: 'github', link: 'https://pepe.543x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/eZ4L3WKdaCHWbocvuA5QhMvR3AwdmhpNfPW9ynHJGx6' },
      { icon: 'mastodon', link: 'https://pepe.543x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/eZ4L3WKdaCHWbocvuA5QhMvR3AwdmhpNfPW9ynHJGx6',
  },
  {
    avatar: './Three/1831.png',
    name: 'BCH',
    title: 'CA:ArXETDYEcKmPWTN7CbLtAtw3bruJbrtwb3FD1RnvXFuf ',
    org: 'BCH',
    orgLink: 'https://www.543x.com',
    desc: 'Scalable, efficient Bitcoin variant with larger blocks.',
    links: [
      { icon: 'github', link: 'https://www.434x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb' },
      { icon: 'mastodon', link: 'https://www.252x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb',
  },
  {
    avatar: './Three/4195.png',
    name: 'FTX',
    title: 'CA:ArXETDYEcKmPWTN7CbLtAtw3bruJbrtwb3FD1RnvXFuf ',
    org: 'FTX',
    orgLink: 'https://dragon.543x.com',
    desc: 'Mysterious, unique, possessing inner strength, exploring the unknown.',
    links: [
      { icon: 'github', link: 'https://www.434x.com'},
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb' },
      { icon: 'mastodon', link: 'https://www.252x.com'},
    ],
    sponsor: 'https://app.meteora.ag/pools/95TETWfUrkUnM6sCSizsQTDJ2tHXBXRZA6mEnjGfpgCb',
  },
]

export const cnTranslator = [
  {
    avatar: './Three/shopify.png',
    name: 'DOG•GO',
    title: 'CA:124XZFhE8ABFYSuDZkxbkKTKjqrB7CpHCspCPsQJPQvL',
    org: 'DOG•GO',
    orgLink: 'http://dog.543x.com/',
    desc: 'Cardano blockchain cryptocurrency for payments and investments.',
    links: [
      { icon: 'github', link: 'http://dog.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/83XaC2jg2FqHMVjcUnHZmcgRL5MvgD45B9FxbK8evosk' },
      { icon: 'mastodon', link: 'http://dog.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/83XaC2jg2FqHMVjcUnHZmcgRL5MvgD45B9FxbK8evosk',
  },
  {
    avatar: './Three/shop.png',
    name: 'JUMP',
    title: 'CA:EgNMgTbTFy1pE15YfhFTpsB97ATpojMWsFPvpHnH8vdV',
    org: 'JUMP',
    orgLink: 'http://jump.543x.com',
    desc: 'community-driven meme coin with a mission to reach the moon.',
    links: [
      { icon: 'github', link: 'http://jump.543x.com' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/9JqQPaU6azN6yRjrRg3MSka4tLeMEKpZ2pe5D3CLnoc' },
      { icon: 'mastodon', link: 'http://jump.543x.com' },
    ],
    sponsor: 'https://app.meteora.ag/pools/9JqQPaU6azN6yRjrRg3MSka4tLeMEKpZ2pe5D3CLnoc',
  },
  {
    avatar: './Three/shopify-inbox.png',
    name: 'A',
    title: 'CA:26BH9BqQQG6WLGoGmWYsW5qd6bM4Bzuz59hBxRAkg6ak',
    org: 'A',
    orgLink: 'https://a.543x.com/',
    desc: 'it combines loneliness, despair, exploration spirit and community power.',
    links: [
      { icon: 'github', link: 'https://a.543x.com/' },
      { icon: 'twitter', link: 'https://app.meteora.ag/pools/8NzwPPEQJFkjRqeBd1jpy3efnvYmgyCk18bqujqiqa4k' },
      { icon: 'mastodon', link: 'https://a.543x.com/' },
    ],
    sponsor: 'https://app.meteora.ag/pools/8NzwPPEQJFkjRqeBd1jpy3efnvYmgyCk18bqujqiqa4k',
  },
]
